#include "ImportExportService.h"

#include "ScriptService.h"
#include "../core/Utf.h"

#include <algorithm>
#include <cwctype>
#include <set>

namespace mezozoy {

bool ImportExportService::isHeading(const std::wstring& rawLine, bool fountain) {
    const std::wstring line = utf::Trim(rawLine); if (line.empty()) return false;
    const std::wstring upper = utf::ToUpper(line);
    if (upper.starts_with(L"ИНТ.") || upper.starts_with(L"НАТ.") || upper.starts_with(L"INT.") || upper.starts_with(L"EXT.")) return true;
    return fountain && line.front() == L'.' && line.size() > 1 && line[1] != L'.';
}

std::wstring ImportExportService::normalizeTitle(std::wstring line, bool fountain) {
    line = utf::Trim(line); if (fountain && !line.empty() && line.front() == L'.') line.erase(line.begin()); return utf::Trim(line);
}

ImportPreview ImportExportService::preview(const std::filesystem::path& path, ScriptExchangeFormat format) const {
    ImportPreview result; result.source = path; result.format = format;
    try {
        const std::wstring content = utf::FromUtf8(utf::ReadFile(path)); const auto lines = utf::SplitLines(content); const bool fountain = format == ScriptExchangeFormat::Fountain;
        std::vector<std::wstring> current; std::set<std::wstring> characters, locations; ScriptService classifier; ScriptLineType previous = ScriptLineType::Empty;
        auto flush = [&] {
            while (!current.empty() && utf::Trim(current.back()).empty()) current.pop_back(); if (current.empty()) return;
            Scene scene; scene.title = normalizeTitle(current.front(), fountain); if (!isHeading(current.front(), fountain)) scene.title = L"ИМПОРТИРОВАННАЯ СЦЕНА";
            scene.heading = scene.title; scene.text = utf::JoinLines(current); scene.summary = L"Импортировано из " + path.filename().wstring(); scene.titleAutoGenerated = false;
            result.scenes.push_back(std::move(scene)); current.clear(); previous = ScriptLineType::Empty;
        };
        for (const auto& sourceLine : lines) {
            std::wstring line = sourceLine;
            if (isHeading(line, fountain)) {
                if (!current.empty()) flush();
                line = normalizeTitle(line, fountain);
                std::wstring location = line; const auto dot = location.find(L'.'); if (dot != std::wstring::npos) location = utf::Trim(location.substr(dot + 1));
                const auto dash = location.find_first_of(L"—–-"); if (dash != std::wstring::npos) location = utf::Trim(location.substr(0, dash)); if (!location.empty()) locations.insert(location);
            }
            current.push_back(line);
            const ScriptLineType type = classifier.classify(line, previous);
            if (type == ScriptLineType::Character) characters.insert(utf::Trim(line));
            if (type != ScriptLineType::Empty) previous = type;
        }
        flush();
        if (result.scenes.empty() && !utf::Trim(content).empty()) { Scene scene; scene.title = path.stem().wstring(); scene.text = content; scene.heading = scene.title; scene.titleAutoGenerated = false; result.scenes.push_back(std::move(scene)); }
        result.detectedCharacters.assign(characters.begin(), characters.end()); result.detectedLocations.assign(locations.begin(), locations.end());
    } catch (const std::exception& error) { result.error = L"Не удалось прочитать файл: " + utf::FromUtf8(error.what()); }
    return result;
}

std::size_t ImportExportService::apply(Project& project, ImportPreview preview, bool addDetectedBibleItems) const {
    if (!preview.error.empty() || preview.scenes.empty()) return 0;
    project.ensureDocumentStructure(); int next = project.nextId(); const int documentId = project.documents.front().id;
    for (auto& scene : preview.scenes) { scene.id = next++; scene.documentId = documentId; scene.orderIndex = static_cast<int>(project.scenes.size()); project.scenes.push_back(std::move(scene)); }
    if (addDetectedBibleItems) {
        for (const auto& name : preview.detectedCharacters) {
            const std::wstring key = utf::ToLower(utf::Trim(name)); bool exists = false;
            for (const auto& item : project.characters) if (utf::ToLower(utf::Trim(item.name)) == key) { exists = true; break; }
            if (!exists) { Character item; item.id = next++; item.name = name; item.shortDescription = L"Найден при импорте"; project.characters.push_back(std::move(item)); }
        }
        for (const auto& name : preview.detectedLocations) {
            const std::wstring key = utf::ToLower(utf::Trim(name)); bool exists = false;
            for (const auto& item : project.locations) if (utf::ToLower(utf::Trim(item.name)) == key) { exists = true; break; }
            if (!exists) { Location item; item.id = next++; item.name = name; item.shortDescription = L"Найдена при импорте"; project.locations.push_back(std::move(item)); }
        }
    }
    project.normalizeOrder(); return preview.scenes.size();
}

bool ImportExportService::exportText(const std::filesystem::path& path, const Project& project, bool fountain, std::wstring* error) const {
    ScriptService scripts; std::wstring text = scripts.buildFullScript(project);
    if (fountain) {
        std::vector<std::wstring> lines = utf::SplitLines(text);
        for (auto& line : lines) if (isHeading(line, true) && !line.empty() && line.front() != L'.') line = L"." + line;
        text = utf::JoinLines(lines);
    }
    return utf::WriteFileAtomic(path, utf::ToUtf8(text), error);
}

}  // namespace mezozoy
