#include "SelfTest.h"

#include "ProjectSerializer.h"
#include "ProjectDocument.h"
#include "PosterService.h"
#include "RecoveryService.h"
#include "ScreenplayDocumentModel.h"
#include "ScreenplayLayoutService.h"
#include "ScriptService.h"
#include "StatisticsService.h"
#include "BreakdownService.h"
#include "GlobalSearchService.h"
#include "ImportExportService.h"
#include "ReviewService.h"
#include "TimelineService.h"
#include "UpdateService.h"
#include "../core/Utf.h"
#include "../ui/Theme.h"

#include <windows.h>

#include <algorithm>
#include <chrono>
#include <cmath>
#include <fstream>
#include <sstream>
#include <stdexcept>

namespace mezozoy {
namespace {

class TestRun {
public:
    void check(bool condition, const std::wstring& message) {
        if (!condition) throw std::runtime_error(utf::ToUtf8(message));
        report_ << L"[OK] " << message << L"\r\n";
    }

    void note(const std::wstring& message) { report_ << L"[INFO] " << message << L"\r\n"; }
    std::wstring report() const { return report_.str(); }

private:
    std::wostringstream report_;
};

std::filesystem::path TestDirectory() {
    wchar_t buffer[MAX_PATH]{};
    const DWORD length = GetTempPathW(MAX_PATH, buffer);
    std::filesystem::path path = length ? std::filesystem::path(buffer) : std::filesystem::temp_directory_path();
    path /= L"Mezozoy-0.9-self-test";
    std::filesystem::create_directories(path);
    return path;
}

bool SameProject(const Project& left, const Project& right) {
    const std::wstring leftPoster = left.posterImageData ? *left.posterImageData : std::wstring{};
    const std::wstring rightPoster = right.posterImageData ? *right.posterImageData : std::wstring{};
    if (left.title != right.title || leftPoster != rightPoster || left.posterImageFormat != right.posterImageFormat ||
        left.genre != right.genre || left.author != right.author || left.year != right.year ||
        left.tagline != right.tagline || left.subtitle != right.subtitle || left.projectType != right.projectType ||
        left.draftLabel != right.draftLabel || left.contact != right.contact || left.copyright != right.copyright ||
        left.logline != right.logline || left.synopsis != right.synopsis || left.scenes.size() != right.scenes.size() ||
        left.characters.size() != right.characters.size() || left.locations.size() != right.locations.size() ||
        left.documents.size() != right.documents.size() || left.worlds.size() != right.worlds.size() ||
        left.references.size() != right.references.size() || left.characterRelations.size() != right.characterRelations.size() ||
        left.timelineEvents.size() != right.timelineEvents.size() || left.productivitySessions.size() != right.productivitySessions.size() ||
        left.folders.size() != right.folders.size() || left.boardSections.size() != right.boardSections.size()) return false;
    for (std::size_t i = 0; i < left.scenes.size(); ++i) {
        const Scene& a = left.scenes[i]; const Scene& b = right.scenes[i];
        if (a.id != b.id || a.title != b.title || a.legacyLocation != b.legacyLocation || a.legacyTimeOfDay != b.legacyTimeOfDay ||
            a.summary != b.summary || a.text != b.text || a.rtf != b.rtf || a.screenplayFormats != b.screenplayFormats || a.orderIndex != b.orderIndex ||
            std::lround(a.cardX) != std::lround(b.cardX) || std::lround(a.cardY) != std::lround(b.cardY) ||
            a.titleAutoGenerated != b.titleAutoGenerated || a.locked != b.locked || a.documentId != b.documentId ||
            a.status != b.status || a.boardColumn != b.boardColumn || a.notes.size() != b.notes.size() ||
            a.breakdownItems.size() != b.breakdownItems.size() || a.reviewComments.size() != b.reviewComments.size()) return false;
    }
    for (std::size_t i = 0; i < left.characters.size(); ++i) {
        const Character& a = left.characters[i]; const Character& b = right.characters[i];
        const std::wstring aAvatar = a.avatarImageData ? *a.avatarImageData : std::wstring{};
        const std::wstring bAvatar = b.avatarImageData ? *b.avatarImageData : std::wstring{};
        if (a.id != b.id || a.name != b.name || a.realName != b.realName || a.role != b.role || a.description != b.description ||
            a.shortDescription != b.shortDescription || a.age != b.age || aAvatar != bAvatar ||
            a.avatarImageFormat != b.avatarImageFormat || a.avatarPath != b.avatarPath ||
            a.profile != b.profile || a.folderId != b.folderId) return false;
    }
    for (std::size_t i = 0; i < left.locations.size(); ++i) {
        const Location& a = left.locations[i]; const Location& b = right.locations[i];
        const std::wstring aImage = a.imageData ? *a.imageData : std::wstring{};
        const std::wstring bImage = b.imageData ? *b.imageData : std::wstring{};
        if (a.id != b.id || a.name != b.name || a.type != b.type || a.description != b.description ||
            a.shortDescription != b.shortDescription || a.interiorExterior != b.interiorExterior ||
            a.timePeriod != b.timePeriod || a.visualMood != b.visualMood || a.notes != b.notes ||
            aImage != bImage || a.imageFormat != b.imageFormat || a.imagePath != b.imagePath ||
            a.profile != b.profile || a.colorHex != b.colorHex || a.folderId != b.folderId ||
            a.archived != b.archived) return false;
    }
    for (std::size_t i = 0; i < left.references.size(); ++i) {
        const ReferenceItem& a = left.references[i]; const ReferenceItem& b = right.references[i];
        const std::wstring aImage = a.imageData ? *a.imageData : std::wstring{};
        const std::wstring bImage = b.imageData ? *b.imageData : std::wstring{};
        if (a.id != b.id || a.title != b.title || a.description != b.description || aImage != bImage ||
            a.imageFormat != b.imageFormat || a.imagePath != b.imagePath || a.aspectRatio != b.aspectRatio ||
            a.tags != b.tags || a.linkedSceneId != b.linkedSceneId ||
            a.linkedCharacterId != b.linkedCharacterId || a.linkedLocationId != b.linkedLocationId) return false;
    }
    for (std::size_t i = 0; i < left.folders.size(); ++i) {
        const DevFolder& a = left.folders[i]; const DevFolder& b = right.folders[i];
        if (a.id != b.id || a.name != b.name || a.section != b.section || a.expanded != b.expanded) return false;
    }
    for (std::size_t i = 0; i < left.boardSections.size(); ++i) {
        const BoardSection& a = left.boardSections[i]; const BoardSection& b = right.boardSections[i];
        if (a.id != b.id || a.name != b.name || std::lround(a.x) != std::lround(b.x) || std::lround(a.y) != std::lround(b.y) ||
            std::lround(a.width) != std::lround(b.width) || std::lround(a.height) != std::lround(b.height) || a.locked != b.locked) return false;
    }
    return true;
}

Project SampleProject() {
    Project project;
    project.title = L"Эхо & живых <0.9>";
    project.posterImageData = std::make_shared<const std::wstring>(L"iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=");
    project.posterImageFormat = L"png";
    project.genre = L"Научная фантастика";
    project.author = L"Автор \"М\"";
    project.year = L"2026";
    project.tagline = L"Помнить, чтобы выжить";
    project.subtitle = L"История станции Горизонт";
    project.projectType = L"Полнометражный фильм";
    project.draftLabel = L"Первый черновик";
    project.contact = L"author@example.test";
    project.copyright = L"© 2026 Автор М";
    project.logline = L"Тест <логлайна> & данных";
    project.synopsis = L"Первая строка.\r\nВторая строка.";

    ProjectDocumentEntry screenplay; screenplay.id = 30; screenplay.type = ProjectDocumentType::Screenplay; screenplay.title = L"Сценарий";
    ProjectDocumentEntry treatment; treatment.id = 31; treatment.type = ProjectDocumentType::Treatment; treatment.title = L"Тритмент"; treatment.text = L"История целиком.";
    project.documents = {screenplay, treatment};

    const std::wstring titles[] = {L"СЦЕНА ОДИН", L"СЦЕНА ДВА", L"СЦЕНА ТРИ"};
    for (int i = 0; i < 3; ++i) {
        Scene scene;
        scene.id = i + 1; scene.documentId = screenplay.id; scene.orderIndex = i; scene.title = titles[i];
        scene.summary = L"Краткое описание " + std::to_wstring(i + 1);
        scene.text = scene.title + L"\r\n\r\nДействие сцены " + std::to_wstring(i + 1) + L".\r\n\r\nГЕРОЙ\r\nРеплика.";
        scene.rtf = L"{\\rtf1 test " + std::to_wstring(i + 1) + L"}";
        scene.cardX = 120.0f + i * 260.0f; scene.cardY = 180.0f; scene.locked = i == 1;
        scene.status = i == 0 ? L"Готово" : L"Черновик"; scene.boardColumn = i == 0 ? L"Акт I" : L"Акт II";
        SceneNote note; note.id = 40 + i; note.text = L"Заметка сцены"; scene.notes.push_back(note);
        BreakdownItem breakdown; breakdown.id = 50 + i; breakdown.sceneId = scene.id; breakdown.category = BreakdownCategory::Prop; breakdown.name = L"Фонарь"; scene.breakdownItems.push_back(breakdown);
        ReviewComment review; review.id = 60 + i; review.sceneId = scene.id; review.commentText = L"Уточнить действие"; scene.reviewComments.push_back(review);
        project.scenes.push_back(std::move(scene));
    }
    DevFolder folder; folder.id = 20; folder.name = L"Главные"; folder.section = L"character"; project.folders.push_back(folder);
    Character character; character.id = 21; character.name = L"МИША"; character.realName = L"Михаил"; character.role = L"Герой";
    character.description = L"Сдержанный & упрямый"; character.shortDescription = L"Главный герой"; character.age = L"27";
    character.avatarImageData = std::make_shared<const std::wstring>(L"iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=");
    character.avatarImageFormat = L"png"; character.avatarPath = L"misha.png";
    character.profile[L"gender"] = L"Мужской"; character.profile[L"dreamcast"] = L"Тестовый актёр";
    character.profile[L"changedBeliefs"] = L"Учится доверять людям"; character.folderId = 20; project.characters.push_back(character);
    Location location; location.id = 22; location.name = L"Бункер"; location.type = L"Помещение";
    location.description = L"Старая подземная станция"; location.shortDescription = L"Укрытие под разрушенным городом";
    location.interiorExterior = L"Интерьер"; location.timePeriod = L"Ближайшее будущее";
    location.visualMood = L"Холодный бетон и аварийный свет"; location.notes = L"Проверить доступ к тоннелю";
    location.imageData = std::make_shared<const std::wstring>(L"iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=");
    location.imageFormat = L"png"; location.imagePath = L"bunker.png";
    location.profile[L"storyFunction"] = L"Последнее безопасное место";
    location.profile[L"architecture"] = L"Бруталистская подземная станция";
    location.profile[L"budgetNotes"] = L"Скрытое устаревшее производственное поле сохраняется";
    project.locations.push_back(location);
    BoardSection section; section.id = 23; section.name = L"Первая серия"; section.x = 90; section.y = 120; section.width = 880; section.height = 500; section.locked = true;
    project.boardSections.push_back(section);
    WorldItem world; world.id = 70; world.name = L"Правила мира"; world.category = L"Лор"; world.description = L"Мир помнит катастрофу"; project.worlds.push_back(world);
    ReferenceItem reference; reference.id = 71; reference.title = L"Архитектура бункера";
    reference.imageData = std::make_shared<const std::wstring>(L"iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=");
    reference.imageFormat = L"png"; reference.imagePath = L"bunker-reference.png"; reference.aspectRatio = L"16:9";
    reference.tags = L"Персонаж · МИША"; reference.linkedCharacterId = character.id; project.references.push_back(reference);
    RelationshipLink relation; relation.id = 72; relation.fromCharacterId = character.id; relation.toCharacterId = character.id; relation.relationType = L"Внутренний конфликт"; project.characterRelations.push_back(relation);
    TimelineEvent event; event.id = 73; event.sceneId = 1; event.act = L"Акт I"; event.episode = L"Пилот"; event.storyTime = L"День 1"; event.durationMinutes = 1.2f; project.timelineEvents.push_back(event);
    return project;
}

void WriteReport(const std::wstring& text) {
    const std::filesystem::path path = TestDirectory().parent_path() / L"Mezozoy-0.9-self-test.log";
    std::ofstream output(path, std::ios::binary | std::ios::trunc);
    const std::string bytes = utf::ToUtf8(text);
    output.write(bytes.data(), static_cast<std::streamsize>(bytes.size()));
}

}  // namespace

int RunSelfTests(const std::filesystem::path& compatibilityProject) {
    TestRun test;
    try {
        const COLORREF greenSelection = ui::Theme::Blend(RGB(32, 33, 38), RGB(34, 197, 94), 34);
        test.check(GetGValue(greenSelection) > GetRValue(greenSelection) &&
                       GetGValue(greenSelection) > GetBValue(greenSelection),
                   L"Цвет выделения наследует выбранный акцент");
        const auto milk = ui::Theme::FromMode(L"Light");
        test.check(milk.light && milk.page == RGB(255, 255, 253) &&
                   ui::Theme::Contrast(milk.text, milk.page) >= 7.0 &&
                   ui::Theme::Contrast(milk.textMuted, milk.panelAlt) >= 4.5 &&
                   ui::Theme::Contrast(milk.text, milk.selection) >= 7.0,
                   L"Молочно-белая тема: контраст текста, подписей и выделения");
        for (COLORREF accent : {RGB(139,92,246), RGB(34,197,94), RGB(249,115,22), RGB(255,255,255), RGB(0,0,0)}) {
            const auto lightAccent = ui::Theme::FromMode(L"Light", accent);
            test.check(ui::Theme::Contrast(lightAccent.accent, lightAccent.panelAlt) >= 4.5 &&
                       ui::Theme::Contrast(lightAccent.text, lightAccent.selection) >= 4.5,
                       L"Светлая тема: акцент и выделение читаемы");
        }
        test.check(ui::Theme::FromMode(L"Dark").background == RGB(15,16,18) &&
                   ui::Theme::FromMode(L"Darker").background == RGB(8,9,11) &&
                   !ui::Theme::FromMode(L"Dark").light && !ui::Theme::FromMode(L"Darker").light,
                   L"Обе графитовые палитры сохранены");
        const std::filesystem::path directory = TestDirectory();
        const std::filesystem::path file = directory / L"roundtrip.mzoy";
        const Project source = SampleProject();
        ProjectSerializer serializer;
        std::wstring error;

        test.check(serializer.save(file, source, &error), L"Новый проект сохраняется: " + error);
        Project loaded;
        test.check(serializer.load(file, loaded, &error), L"Новый проект повторно открывается: " + error);
        test.check(SameProject(source, loaded), L"Все поля проекта проходят XML round-trip без потерь");
        const std::string xml = utf::ReadFile(file);
        test.check(xml.find("&amp;") != std::string::npos && xml.find("&lt;") != std::string::npos,
                   L"Спецсимволы корректно экранируются в XML");
        test.check(xml.find(utf::ToUtf8(L"Эхо")) != std::string::npos, L"Файл проекта записан в UTF-8");
        test.check(xml.find("<PosterImageData>iVBOR") != std::string::npos && loaded.posterImageFormat == L"png",
                   L"Афиша хранится внутри проекта и повторно открывается");
        test.check(xml.find("<Tagline>") != std::string::npos && loaded.tagline == source.tagline &&
                   loaded.subtitle == source.subtitle && loaded.projectType == source.projectType &&
                   loaded.contact == source.contact,
                   L"Расширенная титульная информация проходит XML round-trip");
        test.check(xml.find("<AvatarImageData>iVBOR") != std::string::npos &&
                   loaded.characters.front().avatarImageFormat == L"png" &&
                   loaded.characters.front().avatarImageData &&
                   *loaded.characters.front().avatarImageData == *source.characters.front().avatarImageData,
                   L"Фотография персонажа хранится внутри проекта и повторно открывается");
        test.check(xml.find("<LocationImageData>iVBOR") != std::string::npos &&
                   loaded.locations.front().imageFormat == L"png" &&
                   loaded.locations.front().imageData &&
                   *loaded.locations.front().imageData == *source.locations.front().imageData &&
                   loaded.locations.front().profile.at(L"storyFunction") == L"Последнее безопасное место",
                   L"Досье и фотография локации хранятся внутри проекта и повторно открываются");
        test.check(xml.find("<ReferenceImageData>iVBOR") != std::string::npos &&
                   loaded.references.front().imageData && loaded.references.front().imageFormat == L"png" &&
                   loaded.references.front().aspectRatio == L"16:9" && loaded.references.front().linkedCharacterId == 21,
                   L"Изображение, формат и связь референса проходят XML round-trip");

        const std::filesystem::path avatarFile = directory / L"character-photo.png";
        constexpr unsigned char tinyPng[] = {
            0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A, 0x00, 0x00, 0x00, 0x0D,
            0x49, 0x48, 0x44, 0x52, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01,
            0x08, 0x04, 0x00, 0x00, 0x00, 0xB5, 0x1C, 0x0C, 0x02, 0x00, 0x00, 0x00,
            0x0B, 0x49, 0x44, 0x41, 0x54, 0x78, 0xDA, 0x63, 0x64, 0xF8, 0x0F, 0x00,
            0x01, 0x05, 0x01, 0x01, 0x27, 0x18, 0xE3, 0x66, 0x00, 0x00, 0x00, 0x00,
            0x49, 0x45, 0x4E, 0x44, 0xAE, 0x42, 0x60, 0x82
        };
        {
            std::ofstream avatarOutput(avatarFile, std::ios::binary | std::ios::trunc);
            avatarOutput.write(reinterpret_cast<const char*>(tinyPng), sizeof(tinyPng));
        }
        Character importedAvatar;
        test.check(PosterService::importFile(avatarFile, importedAvatar, &error) &&
                   importedAvatar.avatarImageData && importedAvatar.avatarImageFormat == L"png" &&
                   importedAvatar.avatarPath == avatarFile.filename().wstring() &&
                   PosterService::decode(importedAvatar).size() == sizeof(tinyPng),
                   L"Выбранная фотография персонажа импортируется как переносимый встроенный ресурс");
        Location importedLocation;
        test.check(PosterService::importFile(avatarFile, importedLocation, &error) &&
                   importedLocation.imageData && importedLocation.imageFormat == L"png" &&
                   importedLocation.imagePath == avatarFile.filename().wstring() &&
                   PosterService::decode(importedLocation).size() == sizeof(tinyPng),
                   L"Выбранная фотография локации импортируется как переносимый встроенный ресурс");
        ReferenceItem importedReference;
        test.check(PosterService::importFile(avatarFile, importedReference, &error) &&
                   importedReference.imageData && importedReference.imageFormat == L"png" &&
                   importedReference.imagePath == avatarFile.filename().wstring() &&
                   PosterService::decode(importedReference).size() == sizeof(tinyPng),
                   L"Изображение референса импортируется внутрь проекта");

        Project backupSource = source;
        backupSource.title = L"Вторая версия";
        test.check(serializer.save(file, backupSource, &error), L"Повторное атомарное сохранение работает");
        Project backup;
        test.check(serializer.load(file.wstring() + L".bak", backup, &error), L"Резервная копия открывается");
        test.check(backup.title == source.title, L"Резервная копия содержит предыдущую версию проекта");

        const std::filesystem::path recoveryFile = directory / L"recovery-source.mzoy";
        const std::filesystem::path recoveryAutosave = RecoveryService::AutosavePath(recoveryFile);
        std::filesystem::remove(recoveryFile);
        std::filesystem::remove(recoveryAutosave);
        std::filesystem::remove(RecoveryService::AtomicBackupPath(recoveryFile));
        Project recoveryOriginal = source;
        recoveryOriginal.title = L"Сохраненная версия";
        Project recoveryNewer = source;
        recoveryNewer.title = L"Версия из автосохранения";
        test.check(serializer.save(recoveryFile, recoveryOriginal, &error) && serializer.save(recoveryAutosave, recoveryNewer, &error),
                   L"Подготовлены исходник и автосохранение для проверки восстановления");
        const auto now = std::filesystem::file_time_type::clock::now();
        std::filesystem::last_write_time(recoveryFile, now - std::chrono::minutes(3));
        std::filesystem::last_write_time(recoveryAutosave, now);
        RecoveryService recoveryService;
        const RecoveryScan newerScan = recoveryService.scan(recoveryFile);
        test.check(newerScan.originalValid && newerScan.needsRecovery &&
                    newerScan.candidates[newerScan.recommendedIndex].source == RecoverySource::Autosave,
                    L"Более свежее автосохранение предлагается для восстановления");

        ProjectDocument recoveredDocument;
        recoveredDocument.setBackupPolicy(false, 0);
        test.check(recoveredDocument.openRecovered(recoveryFile, recoveryAutosave, &error) && recoveredDocument.dirty() &&
                    recoveredDocument.filePath() == recoveryFile && recoveredDocument.project().title == recoveryNewer.title,
                    L"Восстановленная копия открывается как несохраненное состояние исходного проекта");
        test.check(recoveredDocument.save(&error) && !std::filesystem::exists(recoveryAutosave),
                    L"Ручное сохранение восстановленного проекта удаляет устаревший автосейв");
        Project recoveredReloaded;
        test.check(serializer.load(recoveryFile, recoveredReloaded, &error) && recoveredReloaded.title == recoveryNewer.title,
                    L"Ctrl+S сохраняет восстановленные данные обратно в исходный файл");

        const std::filesystem::path damagedFile = directory / L"damaged-source.mzoy";
        const std::filesystem::path damagedBackup = RecoveryService::AtomicBackupPath(damagedFile);
        std::filesystem::remove(damagedFile);
        std::filesystem::remove(damagedBackup);
        {
            std::ofstream damaged(damagedFile, std::ios::binary | std::ios::trunc);
            damaged << "<MezozoyProject><broken>";
        }
        test.check(serializer.save(damagedBackup, source, &error), L"Подготовлена валидная атомарная копия поврежденного проекта");
        const RecoveryScan damagedScan = recoveryService.scan(damagedFile);
        test.check(!damagedScan.originalValid && damagedScan.needsRecovery &&
                    damagedScan.candidates[damagedScan.recommendedIndex].source == RecoverySource::AtomicBackup,
                    L"Для поврежденного проекта автоматически находится рабочий .bak");

        ScriptService scripts;
        Project edited = source;
        std::wstring continuous = scripts.buildFullScript(edited);
        const std::wstring oldSecond = L"СЦЕНА ДВА";
        const std::wstring newSecond = L"СЦЕНА ДВА — НОВОЕ НАЗВАНИЕ";
        const std::size_t secondPosition = continuous.find(oldSecond);
        test.check(secondPosition != std::wstring::npos, L"Вторая сцена присутствует в непрерывном документе");
        continuous.replace(secondPosition, oldSecond.size(), newSecond);
        scripts.applyFullScript(edited, continuous);
        test.check(edited.scenes.size() == 3 && edited.scenes[0].title == L"СЦЕНА ОДИН" && edited.scenes[1].title == newSecond && edited.scenes[2].title == L"СЦЕНА ТРИ",
                   L"Переименование второй сцены не повреждает соседние сцены");
        test.check(edited.scenes[2].text.find(L"Действие сцены 3") != std::wstring::npos,
                   L"Текст последующей сцены сохраняется после правки заголовка");

        continuous = scripts.buildFullScript(edited);
        const std::wstring marker = L"Действие сцены 1.";
        const std::size_t markerPosition = continuous.find(marker);
        test.check(markerPosition != std::wstring::npos, L"Тело первой сцены присутствует в документе");
        continuous.replace(markerPosition, marker.size(), L"Действие первой сцены изменено пользователем.");
        scripts.applyFullScript(edited, continuous);
        test.check(edited.scenes[0].text.find(L"изменено пользователем") != std::wstring::npos && edited.scenes[1].title == newSecond,
                   L"Правка тела сцены синхронизируется без разрыва документа");

        ProjectDocument continuousDocument;
        continuousDocument.editProject() = source;
        std::wstring documentText = continuousDocument.fullScript();
        const std::wstring documentMarker = L"Действие сцены 1.";
        const std::size_t documentMarkerPosition = documentText.find(documentMarker);
        const std::wstring untouchedSecondText = source.scenes[1].text;
        const std::wstring untouchedSecondRtf = source.scenes[1].rtf;
        documentText.replace(documentMarkerPosition, documentMarker.size(), L"Текст первой сцены введен в общем редакторе.");
        continuousDocument.applyFullScript(documentText);
        test.check(continuousDocument.project().scenes.size() == source.scenes.size() &&
                   continuousDocument.project().scenes[0].text.find(L"введен в общем редакторе") != std::wstring::npos &&
                   continuousDocument.project().scenes[1].text == untouchedSecondText,
                   L"Редактирование всего сценария меняет нужную сцену и не повреждает соседнюю");
        test.check(continuousDocument.project().scenes[0].rtf.empty() &&
                    continuousDocument.project().scenes[1].rtf == untouchedSecondRtf,
                   L"Общий редактор сбрасывает RTF только у измененной сцены");

        ProjectDocument insertionDocument;
        insertionDocument.editProject() = source;
        const int originalSecondSceneId = source.scenes[1].id;
        const Scene& insertedScene = insertionDocument.addSceneAfter(0);
        test.check(insertionDocument.project().scenes.size() == source.scenes.size() + 1 &&
                   insertionDocument.selectedScene() == 1 &&
                   insertionDocument.project().scenes[1].id == insertedScene.id &&
                   insertionDocument.project().scenes[2].id == originalSecondSceneId,
                   L"Заголовок сцены создает новую сцену сразу после текущей");

        ProjectDocument identityDocument;
        identityDocument.editProject() = source;
        test.check(identityDocument.setSelectedSceneById(originalSecondSceneId) &&
                   identityDocument.moveScene(1, 1) &&
                   identityDocument.selectedSceneId() == originalSecondSceneId &&
                   identityDocument.selectedScene() == 2,
                   L"Единое ядро удерживает выбранную сцену по ID после перестановки");
        test.check(identityDocument.renameSelectedScene(L"СЦЕНА ПО ID") &&
                   identityDocument.sceneById(originalSecondSceneId) &&
                   identityDocument.sceneById(originalSecondSceneId)->title == L"СЦЕНА ПО ID",
                   L"Переименование обновляет ту же сцену для сценария, списка и карточек");
        const std::uint64_t characterRevision = identityDocument.revision();
        test.check(identityDocument.updateCharacter(21, [](Character& item) {
                       if (item.goal == L"Сохранить историю") return false;
                       item.goal = L"Сохранить историю";
                       return true;
                   }, L"Изменение персонажа") &&
                   identityDocument.revision() == characterRevision + 1 &&
                   identityDocument.characterById(21)->goal == L"Сохранить историю",
                   L"Персонаж изменяется атомарно через единое ядро данных");
        const std::uint64_t locationRevision = identityDocument.revision();
        test.check(identityDocument.updateLocation(22, [](Location& item) {
                       if (item.profile[L"danger"] == L"Затопленные нижние уровни") return false;
                       item.profile[L"danger"] = L"Затопленные нижние уровни";
                       return true;
                   }, L"Изменение локации") &&
                   identityDocument.revision() == locationRevision + 1 &&
                   identityDocument.locationById(22)->profile[L"danger"] == L"Затопленные нижние уровни",
                   L"Локация изменяется атомарно через единое ядро данных");
        const std::uint64_t referenceRevision = identityDocument.revision();
        test.check(identityDocument.updateReference(71, [](ReferenceItem& item) {
                       if (item.aspectRatio == L"9:16" && item.linkedCharacterId == 21) return false;
                       item.aspectRatio = L"9:16";
                       item.linkedCharacterId = 21;
                       item.linkedLocationId = 0;
                       return true;
                   }, L"Изменение референса") &&
                   identityDocument.revision() == referenceRevision + 1 &&
                   identityDocument.referenceById(71)->aspectRatio == L"9:16",
                   L"Референс изменяется атомарно через единое ядро данных");
        const std::uint64_t projectRevision = identityDocument.revision();
        test.check(identityDocument.updateProject([](Project& project) {
                       if (project.subtitle == L"Рабочий титул" && project.tagline == L"История начинается здесь") return false;
                       project.subtitle = L"Рабочий титул";
                       project.tagline = L"История начинается здесь";
                       project.projectType = L"Полный метр";
                       return true;
                   }, L"Изменение реквизитов проекта") &&
                   identityDocument.revision() == projectRevision + 1 &&
                   identityDocument.project().subtitle == L"Рабочий титул" &&
                   identityDocument.project().tagline == L"История начинается здесь",
                   L"Титульная страница изменяет проект атомарно через единое ядро данных");
        const std::filesystem::path identityFile = directory / L"data-core-identity.mzoy";
        test.check(identityDocument.saveAs(identityFile, &error), L"Проект единого ядра сохраняется: " + error);
        ProjectDocument identityReloaded;
        test.check(identityReloaded.open(identityFile, &error) &&
                   identityReloaded.sceneById(originalSecondSceneId) &&
                   identityReloaded.sceneById(originalSecondSceneId)->title == L"СЦЕНА ПО ID" &&
                   identityReloaded.characterById(21) &&
                   identityReloaded.characterById(21)->avatarImageData &&
                   identityReloaded.locationById(22) && identityReloaded.locationById(22)->imageData &&
                   identityReloaded.locationById(22)->profile.at(L"danger") == L"Затопленные нижние уровни" &&
                   identityReloaded.referenceById(71) && identityReloaded.referenceById(71)->imageData &&
                   identityReloaded.referenceById(71)->aspectRatio == L"9:16" &&
                   identityReloaded.referenceById(71)->linkedCharacterId == 21 &&
                   identityReloaded.project().subtitle == L"Рабочий титул" &&
                   identityReloaded.project().tagline == L"История начинается здесь" &&
                   identityReloaded.project().projectType == L"Полный метр",
                   L"Сцены, персонажи, локации, реквизиты проекта и фотографии проходят сохранение без потерь");

        Project typedDocument = source;
        const ScreenplayDocumentModel typedSource = ScreenplayDocumentModel::fromProject(typedDocument);
        std::wstring typedText = typedSource.text();
        const std::wstring firstBody = L"Действие сцены 1.";
        const std::wstring thirdBody = L"Действие сцены 3.";
        typedText.replace(typedText.find(firstBody), firstBody.size(), L"Первая сцена изменена в цельном редакторе.");
        typedText.replace(typedText.find(thirdBody), thirdBody.size(), L"Третья сцена тоже изменена без потери границ.");
        const std::wstring typedSecondTitle = L"СЦЕНА ДВА — СИНХРОНИЗИРОВАНА";
        typedText.replace(typedText.find(oldSecond), oldSecond.size(), typedSecondTitle);
        std::wstring screenplayError;
        ScreenplayDocumentModel typedEdits = ScreenplayDocumentModel::parse(
            typedText, typedSource.formatMap(), typedDocument, &screenplayError);
        test.check(typedEdits.apply(typedDocument, &screenplayError),
                   L"Цельный редактор применяет типизированный документ по устойчивым ID сцен");
        test.check(typedDocument.scenes[0].text.find(L"Первая сцена изменена") != std::wstring::npos &&
                   typedDocument.scenes[1].title == typedSecondTitle &&
                   typedDocument.scenes[2].text.find(L"Третья сцена тоже изменена") != std::wstring::npos,
                   L"Несколько правок синхронизируются со сценами и карточками без перераспределения текста");
        test.check(typedSource.text() == scripts.buildFullScript(source) &&
                   typedSource.text().find(L'\uE100') == std::wstring::npos &&
                   typedSource.text().find(L'\uE101') == std::wstring::npos,
                   L"Цельный сценарий, печать и PDF используют один чистый текст без служебных маркеров");

        const ScreenplayDocumentModel structuredSource = ScreenplayDocumentModel::fromProject(source);
        const std::wstring structuredFormats = structuredSource.formatMap();
        std::vector<std::wstring> structuredLines = utf::SplitLines(structuredSource.text());
        const int stableFirstId = source.scenes.front().id;
        structuredLines.front() = L"ИНТ. ПЕРЕИМЕНОВАННАЯ СЦЕНА — НОЧЬ";
        ScreenplayDocumentModel renamedModel = ScreenplayDocumentModel::parse(
            utf::JoinLines(structuredLines), structuredFormats, source, &screenplayError);
        Project renamedStructured = source;
        test.check(renamedModel.apply(renamedStructured, &screenplayError) &&
                   renamedStructured.scenes.size() == source.scenes.size() &&
                   renamedStructured.scenes.front().id == stableFirstId &&
                   renamedStructured.scenes.front().title == structuredLines.front(),
                   L"Типизированный документ переименовывает заголовок без смены ID сцены");

        const std::size_t secondHeading = structuredFormats.find(
            ScriptService::formatCode(ScriptLineType::SceneHeading), 1);
        const std::size_t secondHeadingIndex = secondHeading == std::wstring::npos
            ? structuredFormats.size() : secondHeading;
        std::vector<std::wstring> insertedLines = utf::SplitLines(structuredSource.text());
        insertedLines.insert(insertedLines.begin() + static_cast<std::ptrdiff_t>(secondHeadingIndex),
                             {L"НАТ. НОВАЯ СЦЕНА — ДЕНЬ", L"Новое действие.", L""});
        std::wstring insertedFormats = structuredFormats;
        insertedFormats.insert(secondHeadingIndex, L"HAE");
        ScreenplayDocumentModel insertedModel = ScreenplayDocumentModel::parse(
            utf::JoinLines(insertedLines), insertedFormats, source, &screenplayError);
        Project insertedStructured = source;
        const int oldNextId = source.nextId();
        test.check(secondHeading != std::wstring::npos &&
                   insertedModel.apply(insertedStructured, &screenplayError) &&
                   insertedStructured.scenes.size() == source.scenes.size() + 1 &&
                   insertedStructured.scenes.front().id == stableFirstId &&
                   insertedStructured.scenes[1].id >= oldNextId &&
                   insertedStructured.scenes[2].id == source.scenes[1].id,
                   L"Заголовок внутри цельного текста создаёт сцену и сохраняет ID соседей");

        std::wstring mergedFormats = structuredFormats;
        if (secondHeading != std::wstring::npos)
            mergedFormats[secondHeading] = ScriptService::formatCode(ScriptLineType::Action);
        ScreenplayDocumentModel mergedModel = ScreenplayDocumentModel::parse(
            structuredSource.text(), mergedFormats, source, &screenplayError);
        Project mergedStructured = source;
        test.check(mergedModel.apply(mergedStructured, &screenplayError) &&
                   mergedStructured.scenes.size() + 1 == source.scenes.size() &&
                   mergedStructured.scenes.front().id == stableFirstId &&
                   mergedStructured.scenes.back().id == source.scenes.back().id,
                   L"Снятие формата заголовка объединяет сцены без потери остальных ID");

        const ScreenplayPageSpec letterSpec = ScreenplayLayoutService::pageSpec(ScreenplayPaper::HollywoodLetter);
        const ScreenplayPageSpec a4Spec = ScreenplayLayoutService::pageSpec(ScreenplayPaper::A4);
        test.check(std::abs(letterSpec.widthInches - 8.5) < 0.001 &&
                   std::abs(letterSpec.heightInches - 11.0) < 0.001 &&
                   letterSpec.bodyLineCapacity == 54 && a4Spec.bodyLineCapacity == 58,
                   L"Пресеты Hollywood / US Letter и A4 используют физические размеры независимо от DPI");

        std::wstring onePage;
        std::wstring twoPages;
        for (int line = 0; line < letterSpec.bodyLineCapacity * 2; ++line) {
            if (line) twoPages += L'\n';
            twoPages += L"Короткая печатная строка";
            if (line < letterSpec.bodyLineCapacity) {
                if (!onePage.empty()) onePage += L'\n';
                onePage += L"Короткая печатная строка";
            }
        }
        const std::wstring onePageFormats = L"H" + std::wstring(letterSpec.bodyLineCapacity - 1, L'D');
        const std::wstring twoPageFormats = L"H" + std::wstring(letterSpec.bodyLineCapacity * 2 - 1, L'D');
        test.check(ScriptService::estimatedPrintLines(onePage, onePageFormats) == static_cast<std::size_t>(letterSpec.bodyLineCapacity) &&
                   std::abs(ScriptService::estimatedMinutes(onePage, onePageFormats) - 1.0) < 0.001 &&
                   std::abs(ScriptService::estimatedMinutes(twoPages, twoPageFormats) - 2.0) < 0.001,
                   L"Хронометраж использует реально заполненные страницы: одна страница равна примерно одной минуте");

        Project titleLayoutProject;
        titleLayoutProject.title = L"Название фильма";
        titleLayoutProject.author = L"Автор";
        titleLayoutProject.year = L"2026";
        Scene titleLayoutScene;
        titleLayoutScene.id = 1;
        titleLayoutScene.title = L"ИНТ. ПАВИЛЬОН — ДЕНЬ";
        titleLayoutScene.text = titleLayoutScene.title;
        for (int line = 1; line < letterSpec.bodyLineCapacity; ++line)
            titleLayoutScene.text += L"\nКороткая печатная строка";
        titleLayoutScene.screenplayFormats = onePageFormats;
        titleLayoutProject.scenes.push_back(titleLayoutScene);
        ScreenplayLayoutService screenplayLayout;
        const ScreenplayLayoutDocument titleDocument = screenplayLayout.layout(
            titleLayoutProject, ScreenplayPaper::HollywoodLetter, true);
        test.check(titleDocument.pages.size() == 2 && titleDocument.pages.front().titlePage &&
                   titleDocument.pages[1].scriptPageNumber == 1 && titleDocument.scriptPageCount == 1,
                   L"F12, PDF и печать получают общий документ с отдельным титульным листом");
        {
            Scene styled;
            styled.id = 77; styled.title = L"ИНТ. ЗАЛ - ДЕНЬ";
            styled.text = styled.title + L"\nмолчаливый\n(тихо)\nКороткая реплика.\n\n";
            styled.screenplayFormats = L"HCPDEE";
            Project styledProject; styledProject.scenes.push_back(styled);
            const auto model = ScreenplayDocumentModel::fromProject(styledProject);
            test.check(model.formatMap().starts_with(L"HCPD"), L"Пустые строки в конце сцены не сбрасывают явные типы абзацев");
            styledProject.scenes.push_back(styled);
            styledProject.scenes.back().id = 78;
            const auto exact = ScreenplayDocumentModel::fromProject(styledProject);
            const auto parsedExact = ScreenplayDocumentModel::parse(exact.text(), exact.formatMap(), styledProject);
            Project roundTrip = styledProject;
            parsedExact.apply(roundTrip);
            const auto reopenedExact = ScreenplayDocumentModel::fromProject(roundTrip);
            test.check(exact.text() == reopenedExact.text() && exact.formatMap() == reopenedExact.formatMap() &&
                       exact.text() == scripts.buildFullScript(roundTrip),
                       L"Пустые строки между сценами и в конце не меняются после сохранения и повторного открытия");
            std::wstring longText = L"ИНТ. ЗАЛ - ДЕНЬ\n";
            for (int n = 0; n < 12000; ++n) longText += L"Длинный абзац  с двумя пробелами. ";
            const auto longLayout = screenplayLayout.layoutText(longText, L"HA", ScreenplayPaper::HollywoodLetter);
            bool mapped = longLayout.scriptPageCount > 100;
            std::size_t previousEnd = 0;
            for (const auto& page : longLayout.pages) {
                mapped = mapped && page.usedSlots <= letterSpec.bodyLineCapacity;
                for (const auto& line : page.lines) {
                    mapped = mapped && line.sourceStart >= previousEnd && line.sourceEnd <= longText.size() &&
                        longText.substr(line.sourceStart, line.sourceEnd - line.sourceStart) == line.text &&
                        line.slot < letterSpec.bodyLineCapacity;
                    previousEnd = line.sourceEnd;
                }
            }
            test.check(mapped && previousEnd == longText.size(), L"Длинный абзац на 100+ страницах сохраняет каждый символ и карту курсора");
            std::wstring boundary = L"FIRST";
            for (int line = 1; line < 51; ++line) boundary += L"\nx";
            boundary += L"\nNEXT\n" + std::wstring(100, L'x');
            const auto keptHeading = screenplayLayout.layoutText(boundary, L"H" + std::wstring(50, L'D') + L"HA", ScreenplayPaper::HollywoodLetter);
            test.check(keptHeading.pages.size() == 2 && keptHeading.pages[1].lines.front().text == L"NEXT" &&
                       keptHeading.pages[1].lines.size() == 3,
                       L"Заголовок переносится вместе с первыми строками действия, не оставаясь один внизу страницы");
            const auto viewport = screenplayLayout.layoutText(exact.text(), exact.formatMap(), ScreenplayPaper::A4);
            const auto printed = screenplayLayout.layout(styledProject, ScreenplayPaper::A4, false);
            bool same = viewport.pages.size() == printed.pages.size();
            for (std::size_t p = 0; same && p < viewport.pages.size(); ++p) {
                same = viewport.pages[p].lines.size() == printed.pages[p].lines.size();
                for (std::size_t l = 0; same && l < viewport.pages[p].lines.size(); ++l) {
                    const auto& a = viewport.pages[p].lines[l]; const auto& b = printed.pages[p].lines[l];
                    same = a.text == b.text && a.type == b.type && a.slot == b.slot;
                }
            }
            test.check(same, L"Экран и экспорт используют одинаковые страницы, строки и типы без зависимости от масштаба");
        }
        test.check(ScriptService::nextTypeAfterEnter(ScriptLineType::Character) == ScriptLineType::Dialogue &&
                   ScriptService::nextTypeAfterEnter(ScriptLineType::Dialogue) == ScriptLineType::Action &&
                   ScriptService::nextTypeAfterEnter(ScriptLineType::Parenthetical) == ScriptLineType::Dialogue,
                   L"Умный Enter переключает персонажа в реплику, реплику в действие, а ремарку в реплику");

        ProjectDocument historyDocument;
        historyDocument.createNew();
        historyDocument.setHistoryLimit(2);
        const std::size_t initialSceneCount = historyDocument.project().scenes.size();
        historyDocument.addScene(); historyDocument.addScene(); historyDocument.addScene();
        std::wstring historyLabel;
        test.check(historyDocument.undo(&historyLabel) && historyDocument.project().scenes.size() == initialSceneCount + 2 &&
                    historyDocument.undo() && historyDocument.project().scenes.size() == initialSceneCount + 1 && !historyDocument.undo(),
                    L"История отменяет действия и соблюдает заданный лимит шагов");
        test.check(historyDocument.redo(&historyLabel) && historyDocument.project().scenes.size() == initialSceneCount + 2,
                    L"Отмененное проектное действие можно повторить");
        historyDocument.clearHistory();
        std::wstring untrackedText = historyDocument.fullScript() + L"\r\nТекст без отдельного шага истории.";
        historyDocument.applyFullScript(untrackedText);
        test.check(!historyDocument.canUndo(), L"Печать сценария не создает шаг истории на каждый символ");

        Project manualTitle;
        Scene manualScene;
        manualScene.id = 1; manualScene.title = L"Авторское название"; manualScene.titleAutoGenerated = false;
        manualScene.text = L"ИНТ. СТАРОЕ МЕСТО\r\n\r\nДействие.";
        manualTitle.scenes.push_back(manualScene);
        std::wstring manualText = scripts.buildFullScript(manualTitle);
        const std::wstring newHeading = L"НАТ. НОВОЕ МЕСТО — НОЧЬ";
        manualText.replace(manualText.find(manualScene.title), manualScene.title.size(), newHeading);
        scripts.applyFullScript(manualTitle, manualText);
        test.check(manualTitle.scenes.front().title == newHeading && manualTitle.scenes.front().text.find(newHeading) != std::wstring::npos,
                   L"Название сцены синхронизируется с первой строкой сценария во всех представлениях");

        Project renamedWithRtf = source;
        const std::wstring originalRtf = renamedWithRtf.scenes[1].rtf;
        test.check(scripts.renameScene(renamedWithRtf, 1, L"НОВОЕ РУЧНОЕ НАЗВАНИЕ") &&
                   renamedWithRtf.scenes[1].rtf == originalRtf && renamedWithRtf.scenes[1].text.starts_with(L"НОВОЕ РУЧНОЕ НАЗВАНИЕ"),
                   L"Переименование сцены сохраняет RTF и обновляет только заголовок текста");

        Project tenScenes;
        tenScenes.title = L"Десять сцен";
        for (int index = 0; index < 10; ++index) {
            Scene scene;
            scene.id = index + 1; scene.orderIndex = index; scene.title = L"СЦЕНА " + std::to_wstring(index + 1);
            scene.summary = L"Уникальное описание " + std::to_wstring(index + 1);
            scene.text = scene.title + L"\r\n\r\nУникальный текст " + std::to_wstring(index + 1) + L".\r\n\r\nГЕРОЙ " + std::to_wstring(index + 1) + L"\r\nРеплика.";
            scene.rtf = L"{\\rtf1\\ansi scene" + std::to_wstring(index + 1) + L"}";
            tenScenes.scenes.push_back(std::move(scene));
        }
        tenScenes.ensureDocumentStructure();
        for (auto& scene : tenScenes.scenes) scene.documentId = tenScenes.documents.front().id;
        const std::filesystem::path tenFile = directory / L"ten-scenes.mzoy";
        test.check(serializer.save(tenFile, tenScenes, &error), L"Проект из десяти сцен сохраняется");
        Project tenReloaded;
        test.check(serializer.load(tenFile, tenReloaded, &error) && SameProject(tenScenes, tenReloaded),
                   L"Десять сцен с разными текстами и RTF открываются без потерь");

        Project invalidXmlControls = source;
        invalidXmlControls.scenes.front().rtf += std::wstring(1, L'\0') + std::wstring(1, L'\x0001');
        const std::filesystem::path sanitizedFile = directory / L"sanitized-rtf.mzoy";
        test.check(serializer.save(sanitizedFile, invalidXmlControls, &error), L"RTF с управляющими символами безопасно сохраняется");
        const std::string sanitizedXml = utf::ReadFile(sanitizedFile);
        Project sanitizedReloaded;
        test.check(sanitizedXml.find('\0') == std::string::npos &&
                   serializer.load(sanitizedFile, sanitizedReloaded, &error) &&
                   sanitizedReloaded.scenes.front().rtf.find(L'\0') == std::wstring::npos &&
                   sanitizedReloaded.scenes.front().rtf.find(L'\x0001') == std::wstring::npos,
                   L"Сериализатор удаляет запрещённые XML-символы из RTF");

        test.check(scripts.classify(L"инт. бункер — ночь") == ScriptLineType::SceneHeading &&
                   scripts.classify(L"МИША") == ScriptLineType::Character &&
                   scripts.classify(L"(тихо)") == ScriptLineType::Parenthetical &&
                   scripts.classify(L"CUT TO:") == ScriptLineType::Transition,
                   L"Классификатор распознаёт основные элементы сценария");

        test.check(scripts.classify(L"[старая заметка]") == ScriptLineType::Action &&
                   scripts.classify(L"~старая лирика") == ScriptLineType::Action &&
                   scripts.classify(L"КАДР: общий план") == ScriptLineType::Action &&
                   ScriptService::typeFromFormatCode(ScriptService::formatCode(ScriptLineType::Participants)) == ScriptLineType::Participants &&
                   ScriptService::typeFromFormatCode(ScriptService::formatCode(ScriptLineType::Note)) == ScriptLineType::Note &&
                   ScriptService::typeFromFormatCode(ScriptService::formatCode(ScriptLineType::Shot)) == ScriptLineType::Shot &&
                   ScriptService::typeFromFormatCode(ScriptService::formatCode(ScriptLineType::Lyrics)) == ScriptLineType::Lyrics,
                   L"Импортированные дополнительные типы сохраняются без лишних кнопок в редакторе");

        const std::wstring screenplayMap = scripts.buildFormatMap(
            L"ИНТ. БУНКЕР — НОЧЬ\nМиша входит.\nМИША\n(тихо)\nМы опоздали.\nCUT TO:");
        test.check(screenplayMap == L"HACPDT",
                   L"Карта форматирования сохраняет заголовок, действие, персонажа, ремарку, реплику и переход");

        Project infiniteBoard = source;
        infiniteBoard.scenes.front().cardX = -250000.5f;
        infiniteBoard.scenes.front().cardY = 500000.25f;
        infiniteBoard.boardSections.front().x = -750000.75f;
        infiniteBoard.boardSections.front().y = -625000.5f;
        const std::filesystem::path infiniteBoardFile = directory / L"infinite-board.mzoy";
        Project infiniteBoardReloaded;
        test.check(serializer.save(infiniteBoardFile, infiniteBoard, &error) &&
                   serializer.load(infiniteBoardFile, infiniteBoardReloaded, &error) &&
                   std::fabs(infiniteBoardReloaded.scenes.front().cardX - infiniteBoard.scenes.front().cardX) < 0.1f &&
                   std::fabs(infiniteBoardReloaded.scenes.front().cardY - infiniteBoard.scenes.front().cardY) < 0.1f &&
                   std::fabs(infiniteBoardReloaded.boardSections.front().x - infiniteBoard.boardSections.front().x) < 0.1f &&
                   std::fabs(infiniteBoardReloaded.boardSections.front().y - infiniteBoard.boardSections.front().y) < 0.1f,
                   L"Доска сохраняет карточки и разделы на любых мировых координатах");

        StatisticsService statistics;
        const StatisticsSnapshot stats = statistics.analyze(edited);
        const bool hasMisha = std::any_of(stats.characters.begin(), stats.characters.end(), [](const CharacterStatistics& item) { return item.name == L"МИША"; });
        const bool hasLocations = !stats.locations.empty();
        test.check(stats.scenes.size() == 3 && hasMisha && hasLocations && stats.totalWords > 0,
                   L"Статистика рассчитывается из текущих данных проекта");

        TimelineService timeline;
        ProjectDocument timelineDocument;
        timelineDocument.editProject() = source;
        test.check(timeline.rows(timelineDocument.project()).size() == 3 && timeline.move(timelineDocument, 1, 1),
                   L"Таймлайн использует сцены проекта и безопасно меняет порядок");

        BreakdownService breakdown;
        const std::wstring breakdownReport = breakdown.report(source);
        test.check(breakdownReport.find(L"Фонарь") != std::wstring::npos, L"Разбор сцены формирует содержательный отчёт");

        ReviewService review;
        const std::wstring reviewReport = review.report(source, false);
        test.check(reviewReport.find(L"Уточнить действие") != std::wstring::npos, L"Ревью формирует отчёт по открытым комментариям");

        GlobalSearchService search;
        const auto searchResults = search.search(source, L"Уточнить", 20);
        test.check(!searchResults.empty(), L"Глобальный поиск находит комментарии ревью");

        ImportExportService exchange;
        const std::filesystem::path fountain = directory / L"export.fountain";
        test.check(exchange.exportText(fountain, source, true, &error) && utf::ReadFile(fountain).find("СЦЕНА ОДИН") != std::string::npos,
                   L"Экспорт Fountain содержит сценарий");

        const std::string releaseJson = R"({"tag_name":"v1.2.0","html_url":"https://github.com/LubyStudio/Mezozoy/releases/tag/v1.2.0"})";
        const auto update = UpdateService::parseRelease(releaseJson, L"lubystudio/MEZOZOY", L"1.0.0");
        test.check(UpdateService::isNewerVersion(L"v1.0.1", L"1.0.0") &&
                   !UpdateService::isNewerVersion(L"1.0.0", L"1.0.0") && update &&
                   update->version == L"v1.2.0" &&
                   !UpdateService::parseRelease(releaseJson, L"Another/Repository", L"1.0.0"),
                   L"Автообновление сравнивает версии и принимает только ссылку заданного GitHub-репозитория");

        if (!compatibilityProject.empty()) {
            const std::string originalBytes = utf::ReadFile(compatibilityProject);
            Project legacy;
            test.check(serializer.load(compatibilityProject, legacy, &error), L"Проект Mezozoy 0.8 открывается: " + compatibilityProject.filename().wstring());
            const std::filesystem::path copy = directory / L"legacy-roundtrip.mzoy";
            test.check(serializer.save(copy, legacy, &error), L"Проект 0.8 сохраняется в копию");
            Project reopened;
            test.check(serializer.load(copy, reopened, &error), L"Копия старого проекта повторно открывается");
            test.check(SameProject(legacy, reopened), L"Старый проект проходит round-trip без потери данных");
            test.check(originalBytes == utf::ReadFile(compatibilityProject), L"Исходный проект 0.8 не изменён тестом");
        }

        test.note(L"Все проверки Mezozoy 1.0 завершены успешно.");
        WriteReport(test.report());
        return 0;
    } catch (const std::exception& exception) {
        test.note(L"ОШИБКА: " + utf::FromUtf8(exception.what()));
        WriteReport(test.report());
        return 10;
    } catch (...) {
        test.note(L"ОШИБКА: неизвестное исключение");
        WriteReport(test.report());
        return 11;
    }
}

}  // namespace mezozoy
