#pragma once

#include <algorithm>
#include <cstdint>
#include <map>
#include <memory>
#include <string>
#include <vector>

namespace mezozoy {

enum class ProjectDocumentType {
    Folder,
    Screenplay,
    Episode,
    Season,
    TitlePage,
    Synopsis,
    Treatment,
    Outline,
    BeatSheet,
    Novel,
    ComicBook,
    StagePlay,
    AudioDrama,
    Notes,
    MindMap,
    ReferenceGallery
};

enum class BreakdownCategory {
    Character,
    Extra,
    Location,
    Prop,
    Costume,
    Makeup,
    Vfx,
    Sfx,
    Vehicle,
    Animal,
    Weapon,
    SetDressing,
    Sound,
    Music,
    Stunt,
    Note,
    Custom
};

enum class ReviewMarkType {
    HighlightText,
    HighlightBackground,
    Comment,
    Suggestion,
    Deletion,
    Insertion
};

struct CanvasItem {
    bool locked = false;
    bool selected = false;
    virtual ~CanvasItem() = default;
};

struct SceneNote {
    int id = 0;
    std::wstring title = L"Заметка";
    std::wstring text;
    std::wstring colorHex = L"#A56BFF";
};

struct BreakdownItem {
    int id = 0;
    int sceneId = 0;
    BreakdownCategory category = BreakdownCategory::Note;
    std::wstring name = L"Новый элемент";
    std::wstring description;
    std::wstring assignedTo;
    std::wstring status = L"Не начато";
    std::wstring colorHex = L"#A56BFF";
};

struct ReviewComment {
    int id = 0;
    int sceneId = 0;
    ReviewMarkType type = ReviewMarkType::Comment;
    int startIndex = 0;
    int length = 0;
    std::wstring selectedText;
    std::wstring commentText;
    std::wstring authorName;
    std::wstring colorHex = L"#A56BFF";
    bool resolved = false;
    std::wstring createdAt;
};

struct Scene final : CanvasItem {
    int id = 0;
    int documentId = 0;
    std::wstring title = L"Новая сцена";
    std::wstring heading;
    std::wstring legacyLocation;
    std::wstring legacyTimeOfDay;
    std::wstring summary;
    bool summaryManual = false;
    std::wstring text;
    std::wstring rtf;
    // One compact screenplay element code per paragraph. Kept separately
    // from RTF so the continuous editor can rebuild stable formatting.
    std::wstring screenplayFormats;
    int orderIndex = 0;
    float cardX = -1.0f;
    float cardY = -1.0f;
    bool titleAutoGenerated = true;
    std::wstring boardColumn;
    std::wstring status = L"Черновик";
    std::wstring colorHex = L"#A56BFF";
    std::vector<int> characterIds;
    std::vector<int> locationIds;
    std::vector<SceneNote> notes;
    std::vector<BreakdownItem> breakdownItems;
    std::vector<ReviewComment> reviewComments;
    std::wstring createdAt;
    std::wstring updatedAt;
};

struct Character {
    int id = 0;
    std::wstring name = L"Новый персонаж";
    std::wstring realName;
    std::wstring aliases;
    std::wstring role;
    std::wstring description;
    std::wstring shortDescription;
    std::wstring age;
    std::wstring appearance;
    std::wstring personality;
    std::wstring motivation;
    std::wstring goal;
    std::wstring conflict;
    std::wstring backstory;
    std::wstring arc;
    std::wstring colorHex = L"#A56BFF";
    // New projects keep the character image inside .mzoy. avatarPath remains
    // for opening projects created before embedded character images existed.
    std::shared_ptr<const std::wstring> avatarImageData;
    std::wstring avatarImageFormat;
    std::wstring avatarPath;
    std::map<std::wstring, std::wstring> profile;
    int folderId = 0;
    bool archived = false;
};

struct Location {
    int id = 0;
    std::wstring name = L"Новая локация";
    std::wstring type;
    std::wstring description;
    std::wstring shortDescription;
    std::wstring interiorExterior;
    std::wstring timePeriod;
    std::wstring visualMood;
    std::wstring notes;
    // Location photos are embedded in .mzoy. imagePath is retained only for
    // projects created before portable location images were introduced.
    std::shared_ptr<const std::wstring> imageData;
    std::wstring imageFormat;
    std::wstring imagePath;
    std::map<std::wstring, std::wstring> profile;
    std::wstring colorHex = L"#A56BFF";
    int folderId = 0;
    bool archived = false;
};

struct WorldItem {
    int id = 0;
    std::wstring name = L"Новый элемент мира";
    std::wstring category;
    std::wstring description;
    std::wstring rules;
    std::wstring notes;
    std::vector<int> linkedSceneIds;
};

struct ReferenceItem {
    int id = 0;
    std::wstring title = L"Новый референс";
    std::wstring description;
    std::shared_ptr<const std::wstring> imageData;
    std::wstring imageFormat;
    std::wstring imagePath;
    std::wstring aspectRatio = L"16:9";
    std::wstring tags;
    int linkedSceneId = 0;
    int linkedCharacterId = 0;
    int linkedLocationId = 0;
};

struct RelationshipLink {
    int id = 0;
    int fromCharacterId = 0;
    int toCharacterId = 0;
    std::wstring relationType;
    std::wstring description;
    std::wstring colorHex = L"#A56BFF";
};

struct TimelineEvent {
    int id = 0;
    int sceneId = 0;
    std::wstring title;
    std::wstring act;
    std::wstring episode;
    std::wstring storyTime;
    int orderIndex = 0;
    float durationMinutes = 0.0f;
    std::wstring colorHex = L"#A56BFF";
};

struct ProjectDocumentEntry {
    int id = 0;
    int parentId = 0;
    ProjectDocumentType type = ProjectDocumentType::Screenplay;
    std::wstring title = L"Новый документ";
    int orderIndex = 0;
    bool expanded = true;
    std::wstring text;
    std::wstring rtf;
};

struct ProductivitySession {
    int id = 0;
    std::wstring startedAt;
    std::wstring endedAt;
    int wordsAdded = 0;
    int wordsRemoved = 0;
    int documentId = 0;
    int sceneId = 0;
};

struct DevFolder {
    int id = 0;
    std::wstring name = L"Новая папка";
    std::wstring section = L"character";
    bool expanded = true;
};

struct BoardSection final : CanvasItem {
    int id = 0;
    std::wstring name = L"Новый раздел";
    std::wstring mode = L"free";
    std::wstring colorHex = L"#A56BFF";
    float x = 80.0f;
    float y = 80.0f;
    float width = 980.0f;
    float height = 420.0f;
};

struct Project {
    std::wstring id;
    std::wstring title = L"Новый проект";
    std::shared_ptr<const std::wstring> posterImageData;
    std::wstring posterImageFormat;
    std::wstring genre;
    std::wstring author;
    std::wstring year;
    std::wstring tagline;
    std::wstring subtitle;
    std::wstring projectType;
    std::wstring draftLabel;
    std::wstring contact;
    std::wstring copyright;
    std::wstring logline;
    std::wstring synopsis;
    std::wstring description;
    std::wstring projectFormatVersion = L"0.9";
    std::wstring appVersionCreated = L"0.9";
    std::wstring appVersionLastSaved = L"0.9";
    std::wstring lastSavedAt;
    std::vector<ProjectDocumentEntry> documents;
    std::vector<Scene> scenes;
    std::vector<Character> characters;
    std::vector<Location> locations;
    std::vector<WorldItem> worlds;
    std::vector<ReferenceItem> references;
    std::vector<RelationshipLink> characterRelations;
    std::vector<TimelineEvent> timelineEvents;
    std::vector<ProductivitySession> productivitySessions;
    std::vector<DevFolder> folders;
    std::vector<BoardSection> boardSections;

    int nextId() const {
        int value = 0;
        auto take = [&](int idValue) { value = std::max(value, idValue); };
        for (const auto& item : documents) take(item.id);
        for (const auto& item : scenes) {
            take(item.id);
            for (const auto& note : item.notes) take(note.id);
            for (const auto& breakdown : item.breakdownItems) take(breakdown.id);
            for (const auto& review : item.reviewComments) take(review.id);
        }
        for (const auto& item : characters) take(item.id);
        for (const auto& item : locations) take(item.id);
        for (const auto& item : worlds) take(item.id);
        for (const auto& item : references) take(item.id);
        for (const auto& item : characterRelations) take(item.id);
        for (const auto& item : timelineEvents) take(item.id);
        for (const auto& item : productivitySessions) take(item.id);
        for (const auto& item : folders) take(item.id);
        for (const auto& item : boardSections) take(item.id);
        return value + 1;
    }

    void normalizeOrder() {
        for (std::size_t i = 0; i < scenes.size(); ++i) scenes[i].orderIndex = static_cast<int>(i);
        for (std::size_t i = 0; i < documents.size(); ++i) documents[i].orderIndex = static_cast<int>(i);
    }

    void ensureDocumentStructure() {
        if (documents.empty()) {
            ProjectDocumentEntry screenplay;
            screenplay.id = nextId();
            screenplay.title = title.empty() ? L"Сценарий" : title;
            screenplay.type = ProjectDocumentType::Screenplay;
            documents.push_back(screenplay);
        }
        int screenplayId = documents.front().id;
        for (const auto& document : documents) {
            if (document.type == ProjectDocumentType::Screenplay || document.type == ProjectDocumentType::Episode) {
                screenplayId = document.id;
                break;
            }
        }
        for (auto& scene : scenes) if (scene.documentId == 0) scene.documentId = screenplayId;
    }
};

inline Project CreateDefaultProject() {
    Project project;
    project.title = L"Новый проект";
    Scene scene;
    scene.id = 1;
    scene.orderIndex = 0;
    scene.title = L"НОВАЯ СЦЕНА";
    scene.heading = scene.title;
    scene.text = L"НОВАЯ СЦЕНА\r\n\r\nОписание действия.";
    scene.summary = L"Описание действия.";
    project.scenes.push_back(scene);
    project.ensureDocumentStructure();
    project.scenes.front().documentId = project.documents.front().id;
    return project;
}

}  // namespace mezozoy
